# production container

FROM eclipse-temurin:21-jre-jammy
WORKDIR /opt/tdt/
COPY build/server.jar server.jar
EXPOSE 8080
VOLUME /tdt-data
ENTRYPOINT ["java","-jar","server.jar","--storage.dir=/tdt-data/"]
