# production container

FROM ubuntu:20.04
RUN apt-get update && apt-get install openjdk-17-jre -y --no-install-recommends \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/tdt/
COPY build/server.jar server.jar
EXPOSE 8080
VOLUME /tdt-data
ENTRYPOINT ["java","-jar","server.jar","--storage.dir=/tdt-data/"]
