# production container

FROM eclipse-temurin:17-jre-ubi9-minimal
WORKDIR /opt/tdt/
COPY build/server.jar server.jar
EXPOSE 8080
VOLUME /tdt-data
ENTRYPOINT ["java","-jar","server.jar","--storage.dir=/tdt-data/"]
