name: Build & Publish Docker images

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU (dependency of Docker Buildx)
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u bronkoknorb --password-stdin
      - name: Build
        run: |
          ./build-prod-multi-arch-push.sh
