name: Build & Publish Docker images

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u bronkoknorb --password-stdin
      - name: Build
        # TODO also include arm64 once Raspbian supports that: linux/arm64
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7 \
            --tag bronkoknorb/type-draw-type-game:latest \
            --push \
            .
