name: SonarQube Analysis (tdt-server)

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - 'renovate/**'

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: docker.io/eclipse-temurin:25-jdk-noble

    steps:
      - name: Install Git
        run: apt-get update && apt-get install -y git
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd tdt-server
          ./gradlew -i --no-daemon --stacktrace build sonar
